-- Amounts are integers in the currency's minor unit; never floats.

-- Minimal stand-in: point the foreign keys at your real users table if you have one.
CREATE TABLE users (
    id         BIGSERIAL PRIMARY KEY,
    full_name  TEXT        NOT NULL,
    email      TEXT        NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE credit_companies (
    id             BIGSERIAL PRIMARY KEY,
    name           TEXT        NOT NULL UNIQUE,
    webhook_secret TEXT        NOT NULL, -- HMAC key shared with the provider
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE loans (
    id                BIGSERIAL PRIMARY KEY,
    user_id           BIGINT      NOT NULL REFERENCES users (id),
    credit_company_id BIGINT      NOT NULL REFERENCES credit_companies (id),
    total_amount      BIGINT      NOT NULL CHECK (total_amount > 0), -- total repayable
    term_months       INT         NOT NULL CHECK (term_months BETWEEN 1 AND 120), -- number of monthly installments
    start_date        DATE        NOT NULL,
    -- Money received but not yet applied to an installment (always less than the next unpaid installment).
    credit_balance    BIGINT      NOT NULL DEFAULT 0 CHECK (credit_balance >= 0),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One row per accepted webhook event. The primary key is the idempotency check:
-- a provider re-sending the same event_id can never be applied twice.
CREATE TABLE payments (
    credit_company_id    BIGINT      NOT NULL REFERENCES credit_companies (id),
    event_id             UUID        NOT NULL, -- generated by the provider, reused on retries
    user_id              BIGINT      NOT NULL REFERENCES users (id),
    loan_id              BIGINT      NOT NULL REFERENCES loans (id),
    amount               BIGINT      NOT NULL CHECK (amount > 0),
    paid_at              TIMESTAMPTZ NOT NULL, -- payment time as reported by the provider
    credit_balance_after BIGINT      NOT NULL CHECK (credit_balance_after >= 0), -- lets a duplicate replay the original answer
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (credit_company_id, event_id)
);

-- A loan's payment history.
CREATE INDEX payments_loan_paid_idx ON payments (loan_id, paid_at);

CREATE TABLE installments (
    id                 BIGSERIAL PRIMARY KEY,
    loan_id            BIGINT      NOT NULL REFERENCES loans (id),
    user_id            BIGINT      NOT NULL REFERENCES users (id),
    credit_company_id  BIGINT      NOT NULL REFERENCES credit_companies (id),
    installment_number INT         NOT NULL CHECK (installment_number > 0),
    amount             BIGINT      NOT NULL CHECK (amount > 0),
    due_date           DATE        NOT NULL,
    status             TEXT        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid')),
    paid_at            TIMESTAMPTZ, -- provider-reported time of the payment that settled it
    payment_event_id   UUID,        -- the payment that settled it
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (loan_id, installment_number),
    -- A paid installment points at a real payment, and that payment must belong to the same
    -- company. Not enforced while payment_event_id is NULL (pending rows).
    FOREIGN KEY (credit_company_id, payment_event_id) REFERENCES payments (credit_company_id, event_id),
    -- Paid rows always carry both payment fields; pending rows carry neither.
    CHECK (
        (status = 'paid'    AND paid_at IS NOT NULL AND payment_event_id IS NOT NULL) OR
        (status = 'pending' AND paid_at IS NULL     AND payment_event_id IS NULL)
    )
);

-- A user's schedule, ordered by date.
CREATE INDEX installments_user_due_idx ON installments (user_id, due_date);

-- Overdue = status 'pending' AND due_date < today; derived, so no stored state to keep in sync.
CREATE INDEX installments_pending_due_idx ON installments (due_date) WHERE status = 'pending';

-- What a payment settled (also serves the foreign-key checks against payments).
CREATE INDEX installments_payment_idx
    ON installments (credit_company_id, payment_event_id)
    WHERE payment_event_id IS NOT NULL;
