// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"interview/internal/handler"
	"interview/internal/repo"
	"interview/internal/service"
)

// Injectors from wire.go:

// Initialize builds the whole object graph. This file is only read by the wire
// tool; the generated implementation lives in wire_gen.go.
func Initialize(cfg Config) (*App, func(), error) {
	logger, cleanup, err := ProvideLogger(cfg)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := ProvideDB(cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	creditCompanyRepo := repo.NewCreditCompanyRepo(db)
	loanRepo := repo.NewLoanRepo(db)
	installmentRepo := repo.NewInstallmentRepo(db)
	paymentRepo := repo.NewPaymentRepo(db)
	txManager := repo.NewTxManager(db)
	paymentService := service.NewPaymentService(creditCompanyRepo, loanRepo, installmentRepo, paymentRepo, txManager)
	engine := handler.NewRouter(paymentService, logger)
	server := ProvideHTTPServer(cfg, engine, logger)
	app := &App{
		Server: server,
		Log:    logger,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
